RD

diff --git a/.readthedocs.yaml b/.readthedocs.yaml
--- a/.readthedocs.yaml
+++ b/.readthedocs.yaml
@@ -15,22 +15,24 @@ build:
   os: "ubuntu-22.04"
   tools:
     python: "3.8"
-  jobs:
-    pre_create_environment:
-       - conda update --yes --quiet --name=rtd38 --channel=defaults conda
+    nodejs: "18"
 
-    post_checkout:
-      # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
-      #
-      # Cancel building pull requests when there aren't changed in the docs directory.
-      #
-      # If there are no changes (git diff exits with 0) we force the command to return with 183.
-      # This is a special exit code on Read the Docs that will cancel the build immediately.
-      - |
-        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yml requirements/docs.txt;
-        then
-          echo "No changes to docs/ - exiting the build.";
-          exit 183;
-        fi
+  # jobs:
+  #   # pre_create_environment:
+  #   #    - conda update --yes --quiet --name=rtd38 --channel=defaults conda
+
+  #   post_checkout:
+  #     # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
+  #     #
+  #     # Cancel building pull requests when there aren't changed in the docs directory.
+  #     #
+  #     # If there are no changes (git diff exits with 0) we force the command to return with 183.
+  #     # This is a special exit code on Read the Docs that will cancel the build immediately.
+  #     - |
+  #       if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yml requirements/docs.txt;
+  #       then
+  #         echo "No changes to docs/ - exiting the build.";
+  #         exit 183;
+  #       fi
 conda:
     environment: environment.yml
